minors

diff --git a/sh/banner b/sh/banner
--- a/sh/banner
+++ b/sh/banner
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
 
-set -e # e  exit if a commands returns a non-zero value
+# set -e # e  exit if a commands returns a non-zero value
 
-echo -e "\033[01;35m\n\n\n"
-toilet --width "$(($(tput cols) - 18))" --font future --filter border "  $@  " | sed 's/^/        /'
-echo -e "\033[00m\n\n"
+# echo -e "\033[01;35m\n\n\n"
+# toilet --width "$(($(tput cols) - 18))" --font future --filter border "  $@  " | sed 's/^/        /'
+# echo -e "\033[00m\n\n"
+
+# cargo install cfonts
+all="$@"
+cfonts "$all" --colors "#758,#630" -a center -f grid
+
