sh/wakeful

diff --git a/sh/suunto_report b/sh/suunto_report
--- a/sh/suunto_report
+++ b/sh/suunto_report
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e # exit if a commands returns a non-zero value
+
 HELP="
 suunto_report 1.0.0
 Luca Pinelli
@@ -39,41 +41,43 @@ fi
 
 pdf_name="$1"
 csv_name="$(echo "$pdf_name" | sd '\.pdf$' '.csv')"
-db_file_name="$(echo "$pdf_name" | sd '\.pdf$' '.sqlite.db')"
 
-pdftotext "$pdf_name" /tmp/suunto_report.txt
-rg '[\w\d]' /tmp/suunto_report.txt | sd '^[^\w\d]*([\w\d ]+)[^\w\d]*$' '$1' > /tmp/suunto_report_nobl.txt
-printf "id,year,month,day,time,duration,max depth,avg depth\n" > "$csv_name"
-i=0
-while read line
-do
-  i=$((i + 1))
-  if ((i < 21)); then # exclude the first 20 lines
-    continue
-  fi
-  module=$(( (i - 20) % 8 ))
-  if ((module == 1)); then
-    id="$line"
-  elif ((module == 2)); then
-    # date="$line"
-    split=(${line//\// })
-    year=${split[2]}
-    month=${split[0]}
-    day=${split[1]}
-  elif ((module == 3)); then
-    time="$line"
-  elif ((module == 4)); then
-    # duration="$line"
-    duration="$(echo $line | sd '^0:(\d\d).(\d\d)$' '($1 * 60) + $2' | bc)"
-  elif ((module == 5)); then
-    max_depth="$(echo "$line" | sd '^([\d.]+)[^\d]*$' '$1')"
-  elif ((module == 6)); then
-    avg_depth="$(echo "$line" | sd '^([\d.]+)[^\d]*$' '$1')"
-    printf "$id,$year,$month,$day,$time,$duration,$max_depth,$avg_depth\n" >> "$csv_name"
-  fi
-done < /tmp/suunto_report_nobl.txt
+create_csv() {
+  pdftotext "$pdf_name" /tmp/suunto_report.txt
+  rg '[\w\d]' /tmp/suunto_report.txt | sd '^[^\w\d]*([\w\d ]+)[^\w\d]*$' '$1' > /tmp/suunto_report_nobl.txt
+  printf "id,year,month,day,time,duration,max depth,avg depth\n" > "$csv_name"
+  i=0
+  while read line
+  do
+    i=$((i + 1))
+    if ((i < 21)); then # exclude the first 20 lines
+      continue
+    fi
+    module=$(( (i - 20) % 8 ))
+    if ((module == 1)); then
+      id="$line"
+    elif ((module == 2)); then
+      # date="$line"
+      split=(${line//\// })
+      year=${split[2]}
+      month=${split[0]}
+      day=${split[1]}
+    elif ((module == 3)); then
+      time="$line"
+    elif ((module == 4)); then
+      # duration="$line"
+      duration="$(echo $line | sd '^0:(\d\d).(\d\d)$' '($1 * 60) + $2' | bc)"
+    elif ((module == 5)); then
+      max_depth="$(echo "$line" | sd '^([\d.]+)[^\d]*$' '$1')"
+    elif ((module == 6)); then
+      avg_depth="$(echo "$line" | sd '^([\d.]+)[^\d]*$' '$1')"
+      printf "$id,$year,$month,$day,$time,$duration,$max_depth,$avg_depth\n" >> "$csv_name"
+    fi
+  done < /tmp/suunto_report_nobl.txt
+}
 
-banner csv
+echo "extract the data from the PDF and create the CSV file..."
+create_csv
 
 echo "
 ╭────────────╮
@@ -87,7 +91,10 @@ echo "
 │ SQLite 3 execution log │
 ╰────────────────────────╯
 "
-banner sqlite3
+
+db_file_name="$(echo "$pdf_name" | sd '\.pdf$' '.sqlite.db')"
+
+echo "> SQLite 3 Database: ${db_file_name}"
 echo '> remove old DB'
 rm -f "$db_file_name"
 echo '> create table "freedive"'
@@ -111,143 +118,151 @@ echo "
 delete from freedive where id = 'id'
 " | sqlite3 "$db_file_name"
 
+
 banner reports
-echo "
-╭──────────────╮
-│ Top duration │
-╰──────────────╯
-"
-echo ".mode columns
-select
-    top_duration.year,
-    top_duration.month,
-    top_duration.day,
-    top_duration.duration,
-    max(depth.depth) depth
-from (
-    -- top_duration
-    select
-        year,
-        month,
-        day,
-        duration duration_secs,
-        (max(duration) / 60) || ':' || substr('0' || (max(duration) % 60), -2, 2) duration
-    from freedive
-    group by year, month, day
-) top_duration
-join (
-    select year, month, day, duration, max(max_depth) depth
-    from freedive
-    group by year, month, day, duration
-) depth
-    on top_duration.year = depth.year
-    and top_duration.month = depth.month
-    and top_duration.day = depth.day 
-    and top_duration.duration_secs = depth.duration
-group by
-    top_duration.year,
-    top_duration.month,
-    top_duration.day,
-    top_duration.duration
-order by top_duration.duration desc, top_duration.year, top_duration.month, top_duration.day
-limit 10
-" | sqlite3 "$db_file_name"
 
-echo "
-╭───────────╮
-│ Top depth │
-╰───────────╯
-"
-echo ".mode columns
-select
-    top_depth.year,
-    top_depth.month,
-    top_depth.day,
-    top_depth.depth,
-    (max(duration.duration) / 60) || ':' || substr('0' || (max(duration.duration) % 60), -2, 2) duration
-from (
-    -- top_depth
-    select year, month, day, max(max_depth) depth
-    from freedive
-    group by year, month, day
-) top_depth
-join (
-    select year, month, day, max_depth, max(duration) duration
-    from freedive
-    group by year, month, day, max_depth
-) duration
-    on top_depth.year = duration.year
-    and top_depth.month = duration.month
-    and top_depth.day = duration.day 
-    and top_depth.depth = duration.max_depth
-group by
-    top_depth.year,
-    top_depth.month,
-    top_depth.day,
-    top_depth.depth
-order by top_depth.depth desc, top_depth.year, top_depth.month, top_depth.day
-limit 10
-" | sqlite3 "$db_file_name"
-echo
-
-echo "
-╭──────────────╮
-│ Last 10 days │
-╰──────────────╯
-"
-echo ".mode columns
-select *
-from (
-    -- report
+report () {
+    echo "
+    ╭──────────────╮
+    │ Top duration │
+    ╰──────────────╯
+    "
+    echo ".mode columns
     select
-        -- row_number() over (order by deep.year, deep.month, deep.day) as row_number,
-        deep.year,
-        deep.month,
-        deep.day,
-        '(' || deep.duration || ') ' || deep.max_depth max_depth,
-        '(' || long.duration || ') ' || long.max_depth max_duration
+        top_duration.year,
+        top_duration.month,
+        top_duration.day,
+        top_duration.duration,
+        max(depth.depth) depth
     from (
-        -- deep
+        -- top_duration
         select
-            freedive.year,
-            freedive.month,
-            freedive.day,
-            freedive.max_depth,
-            (max(freedive.duration) / 60) || ':' || substr('0' || (max(freedive.duration) % 60), -2, 2) duration
-        from freedive 
-        join (
-            select year, month, day, max(max_depth) max_depth
-            from freedive
-            group by year, month, day
-        ) deepdive
-            on freedive.year = deepdive.year
-            and freedive.month = deepdive.month
-            and freedive.day = deepdive.day
-            and freedive.max_depth = deepdive.max_depth
-        group by freedive.year, freedive.month, freedive.day, freedive.max_depth
-    ) deep
+            year,
+            month,
+            day,
+            duration duration_secs,
+            (max(duration) / 60) || ':' || substr('0' || (max(duration) % 60), -2, 2) duration
+        from freedive
+        group by year, month, day
+    ) top_duration
     join (
-        -- long
-        select
-            freedive.year,
-            freedive.month,
-            freedive.day,
-            max(freedive.max_depth) max_depth,
-            (freedive.duration / 60) || ':' || substr('0' || (freedive.duration % 60), -2, 2) duration
-        from freedive 
-        join (select year, month, day, max(duration) max_duration
-            from freedive
-            group by year, month, day
-        ) longdive
-            on freedive.year = longdive.year
-            and freedive.month = longdive.month
-            and freedive.day = longdive.day
-            and freedive.duration = longdive.max_duration
-        group by freedive.year, freedive.month, freedive.day, freedive.duration
-    ) long on deep.year = long.year and deep.month = long.month and deep.day = long.day
-    order by deep.year desc, deep.month  desc, deep.day desc
+        select year, month, day, duration, max(max_depth) depth
+        from freedive
+        group by year, month, day, duration
+    ) depth
+        on top_duration.year = depth.year
+        and top_duration.month = depth.month
+        and top_duration.day = depth.day
+        and top_duration.duration_secs = depth.duration
+    group by
+        top_duration.year,
+        top_duration.month,
+        top_duration.day,
+        top_duration.duration
+    order by top_duration.duration desc, top_duration.year, top_duration.month, top_duration.day
     limit 10
-) report
-order by year, month, day
-" | sqlite3 "$db_file_name"
-echo
+    " | sqlite3 "$db_file_name"
+
+    echo "
+    ╭───────────╮
+    │ Top depth │
+    ╰───────────╯
+    "
+    echo ".mode columns
+    select
+        top_depth.year,
+        top_depth.month,
+        top_depth.day,
+        top_depth.depth,
+        (max(duration.duration) / 60) || ':' || substr('0' || (max(duration.duration) % 60), -2, 2) duration
+    from (
+        -- top_depth
+        select year, month, day, max(max_depth) depth
+        from freedive
+        group by year, month, day
+    ) top_depth
+    join (
+        select year, month, day, max_depth, max(duration) duration
+        from freedive
+        group by year, month, day, max_depth
+    ) duration
+        on top_depth.year = duration.year
+        and top_depth.month = duration.month
+        and top_depth.day = duration.day
+        and top_depth.depth = duration.max_depth
+    group by
+        top_depth.year,
+        top_depth.month,
+        top_depth.day,
+        top_depth.depth
+    order by top_depth.depth desc, top_depth.year, top_depth.month, top_depth.day
+    limit 10
+    " | sqlite3 "$db_file_name"
+    echo
+
+    echo "
+    ╭──────────────╮
+    │ Last 20 days │
+    ╰──────────────╯
+    "
+    echo ".mode columns
+    select *
+    from (
+        -- report
+        select
+            -- row_number() over (order by deep.year, deep.month, deep.day) as row_number,
+            deep.year,
+            deep.month,
+            deep.day,
+            '(' || deep.duration || ') ' || deep.max_depth max_depth,
+            '(' || long.duration || ') ' || long.max_depth max_duration
+        from (
+            -- deep
+            select
+                freedive.year,
+                freedive.month,
+                freedive.day,
+                freedive.max_depth,
+                (max(freedive.duration) / 60) || ':' || substr('0' || (max(freedive.duration) % 60), -2, 2) duration
+            from freedive
+            join (
+                select year, month, day, max(max_depth) max_depth
+                from freedive
+                group by year, month, day
+            ) deepdive
+                on freedive.year = deepdive.year
+                and freedive.month = deepdive.month
+                and freedive.day = deepdive.day
+                and freedive.max_depth = deepdive.max_depth
+            group by freedive.year, freedive.month, freedive.day, freedive.max_depth
+        ) deep
+        join (
+            -- long
+            select
+                freedive.year,
+                freedive.month,
+                freedive.day,
+                max(freedive.max_depth) max_depth,
+                (freedive.duration / 60) || ':' || substr('0' || (freedive.duration % 60), -2, 2) duration
+            from freedive
+            join (select year, month, day, max(duration) max_duration
+                from freedive
+                group by year, month, day
+            ) longdive
+                on freedive.year = longdive.year
+                and freedive.month = longdive.month
+                and freedive.day = longdive.day
+                and freedive.duration = longdive.max_duration
+            group by freedive.year, freedive.month, freedive.day, freedive.duration
+        ) long on deep.year = long.year and deep.month = long.month and deep.day = long.day
+        order by deep.year desc, deep.month  desc, deep.day desc
+        limit 20
+    ) report
+    order by year desc, month desc, day desc
+    " | sqlite3 "$db_file_name"
+    echo
+}
+
+report > report.txt
+
+cat report.txt
