sh/wakeful use xprintidle

diff --git a/sh/wakeful b/sh/wakeful
--- a/sh/wakeful
+++ b/sh/wakeful
@@ -4,7 +4,7 @@ set -e # exit if a commands returns a non-zero value
 
 HELP="
 NAME
-  wakeful - do not leet you laptop to sleep
+  wakeful - do not let your laptop to sleep
 
 USAGE
   wakeful [interval]
@@ -15,11 +15,17 @@ ARGS
 
 REQUIRES
   xdotool (sudo apt install xdotool)
+  xprintidle (sudo apt install xprintidle)
 "
 
 if ! command -v xdotool &> /dev/null
 then
     echo "Command xdotool not found, install it using: sudo apt install xdotool"
+    exit
+fi
+if ! command -v xprintidle &> /dev/null
+then
+    echo "Command xprintidle not found, install it using: sudo apt install xprintidle"
     exit
 fi
 
@@ -35,50 +41,24 @@ if [[ ! -z $1 ]] ; then
   fi
 fi
 
-# if [ "$(type -t banner)" == "file" ]
+mkdir -p /tmp/wakeful_logs
+log_file="/tmp/wakeful_logs/wakeful_$(date +%Y%m%d_%H%M).log"
+
 if command -v banner &> /dev/null
 then
     banner wakeful
 fi
 
-echo "started at $(date) (interval $interval seconds)"
-echo
-
-mouse_x=0
-mouse_y=0
-mouse_screen=0
-mouse_window=0
-update_mouse_location () {
-  eval "$(xdotool getmouselocation --shell)" #  this will set the variables: X, Y, SCREEN, WINDOW
-  mouse_x="$X"
-  mouse_y="$X"
-  mouse_screen="$SCREEN"
-  mouse_window="$WINDOW"
-}
-
-previous_x=0
-previous_y=0
-previous_screen=0
-previous_window=0
-update_previous_location () {
-  update_mouse_location
-  previous_x=$mouse_x
-  previous_y=$mouse_y
-  previous_screen=$mouse_screen
-  previous_window=$mouse_window
-}
-
-update_previous_location
+echo "started at $(date) (interval $interval seconds)" | tee -a "$log_file"
+echo | tee -a "$log_file"
 
 woke=0
 awaken () {
-  update_mouse_location
-
-  # if mouse not moved
-  if (( previous_x == mouse_x && previous_y == mouse_y && previous_screen == mouse_screen )); then
+  # if the IDLE time is more than the interval time
+  if (( $(xprintidle) > ($interval * 1000) )); then
     # do not let the laptop to go asleep
     woke=$((++woke))
-    echo -e "\e[1A\e[Kwakeful $(date) (#${woke}, $(((woke * interval) / 60)) minutes)"
+    echo -e "\e[1A\e[Kwakeful $(date) (#${woke}, $(((woke * interval) / 60)) minutes)" | tee -a "$log_file"
     xdotool mousemove_relative -- 0 -10
     xdotool sleep 0.1
     xdotool mousemove_relative -- -10 0
@@ -88,12 +68,10 @@ awaken () {
     xdotool mousemove_relative 10 0
   else
     if (( woke != 0 )); then
-      echo
+      echo | tee -a "$log_file"
     fi
     woke=0
   fi
-
-  update_previous_location
 }
 
 while true; do
